version: 2
updates:
  - package-ecosystem: npm
    directory: /creator-fe
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /creator-fe/api
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /redirect
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /creator-api
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
