name: Deploy Redirect Service

on:
  push:
    branches:
      - main
    paths:
      - 'redirect/**'
      - '.github/workflows/deploy-redirect.yml'
      - '.github/workflows/deploy-template.yml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service_name: redirect
      container_app_name: clinten-redirect
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}