name: Deploy Creator API

on:
  push:
    branches:
      - main
    paths:
      - 'creator-api/**'
      - '.github/workflows/deploy-creator-api.yml'
      - '.github/workflows/deploy-template.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service_name: creator-api
      container_app_name: clinten-creator-api
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}