name: Deploy Creator UI

on:
  push:
    branches:
      - main
    paths:
      - 'creator-fe/**'
      - '.github/workflows/deploy-creator-fe.yml'
      - '.github/workflows/deploy-fe-template.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-fe-template.yml
    with:
      environment: prod
      health_url: https://ashy-meadow-07aae3f0f.7.azurestaticapps.net/api/health
    secrets:
      SWA_DEPLOYMENT_TOKEN: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
