name: Deploy Creator UI (Stage)

on:
  push:
    branches:
      - dev
    paths:
      - 'creator-fe/**'
      - '.github/workflows/deploy-creator-fe-stage.yml'
      - '.github/workflows/deploy-fe-template.yml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-fe-template.yml
    with:
      environment: stage
      health_url: https://red-desert-04141eb0f.7.azurestaticapps.net/api/health
    secrets:
      SWA_DEPLOYMENT_TOKEN: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
