name: PR Checks - Redirect

on:
  pull_request:
    paths:
      - 'redirect/**'
      - '.github/workflows/pr-redirect.yml'
      - '.github/workflows/pr-go-template.yml'

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/pr-go-template.yml
    with:
      service: redirect
      coverage_threshold: 90
